### ISSUE TITLE
Any way to add camera feeds to Homekit?

### ISSUE THREAD

**Issue by rob74lee** [daymondm/homebridge-vivint#1]
This plugin is awesome! The only thing missing is the ability to add cameras. Hopefully this can be done! Great job sir!

**Comment by daymondm** [comment]
Not that I have been able to figure out yet. Trying to work out a way to access the camera's RTSP feeds but they are password protected and I haven't gotten through that. Thanks!

**Comment by rob74lee** [comment]
No worries! I can assist if needed! I would more than welcome an opportunity to help here! Thanks again!

**Comment by daymondm** [comment]
I was able to find the password for it today and got a working feed in HomeKit ... so coming soon 😁

**Comment by rob74lee** [comment]
Very, very exciting news!! Thank you for the update!

**Comment by daymondm** [comment]
So I decided to leave the camera feeds separate from this plugin. The reason why is because the cameras are standard RTSP feeds and there is already a plugin written that works perfectly, and it made more sense to me to just configure them in that plugin since you would have to download and install that plugin regardless because it would be a dependency. Also that way I don't need to spend several days trying to learn more javascript!

All that said, I'll show you the steps I took to get all of my cameras working in HomeKit.

Prerequisites:
1. Install [FFMpeg](https://ffmpeg.org/download.html). If you are compiling your own, make sure it is configured with libfdk_aac or you will not have audio support. If you don't wish to have audio, then ignore that advice.
2. Download [homebridge-camera-ffmpeg](https://www.npmjs.com/package/homebridge-camera-ffmpeg)

Now we still need to get the password to the RTSP feeds, ID#'s of the cameras, and the IP address of the panel.

- Password to RTPS feeds
-- You will need to use Chrome to follow these directions. Thankfully, on Vivint's sky panel website, they toss around the password in plain text. It is quite hidden behind some javascript, but follow me on the instructions and we can get the website to print it out for us.
-- Log in to your vivintsky.com account (in chrome)
-- Open developer tools (view -> developer -> developer tools).
-- Click on the sources tab
-- Make sure you are looking at "app.js"
-- Click the { } icon at the bottom left of the developer screen to pretty-print the source and make it readable
-- <img width="807" alt="Screen Shot 2019-05-09 at 10 37 51 AM" src="https://user-images.githubusercontent.com/48080138/57466951-380aff00-7247-11e9-8d4c-c55f468cbd9f.png">
-- Use ⌘F (or ctrl + F) to open a Find prompt and search for: `r.on("apiReady", function()` There should be only one result, and as of today is on line 13918 of app.js:formatted.
-- So here is the function we are looking at:

```
                    r.on("apiReady", function() {
                        if (!e.isDemo)
                            var t = E.get({
                                systemId: a.id
                            }, function() {
                                var e = "rtsp://".length;
                                n = n.slice(0, e) + t[S.Name] + ":" + t[S.Password] + "@" + n.slice(e),
                                r.pingRTSPServer(n)
                            })
                    }))
```

-- What we want to do is insert a breakpoint to make the code STOP when we reach that function, and we are going to insert some javascript code to make it print out that t[S.Password] variable into the console log because it has the plain text copy of the password to your cameras.
-- Click on the line number that contains the r.on("apiReady" text. It should turn the numbers blue and create a breakpoint.
-- Hit refresh on the page, and the page should PAUSE when it reaches your breakpoint. You should also notice at this point that some of the information in the app.js:formatted screen will be filled in. The IP address of your camera is available there.
-- <img width="1900" alt="Screen Shot 2019-05-09 at 10 50 49 AM" src="https://user-images.githubusercontent.com/48080138/57467662-8ec50880-7248-11e9-91b3-c739e6fd85e4.png">
-- Ok here's where the magic happens. Down in the bottom make sure "Console" is selected (not the What's New tab) and we are going to insert our own version of the function its about to run.
-- Copy/paste this into the console:
```
                            var t = E.get({
                                systemId: a.id
                            }, function() {
                                var e = "rtsp://".length; console.log(t[S.Password]);
                                n = n.slice(0, e) + t[S.Name] + ":" + t[S.Password] + "@" + n.slice(e),
                                r.pingRTSPServer(n)
                            })
```
-- The console should reply to you, "<- undefined"
-- Now hit the play button to tell the debugger to continue
-- 
<img width="1905" alt="Screen Shot 2019-05-09 at 10 55 04 AM" src="https://user-images.githubusercontent.com/48080138/57467986-38a49500-7249-11e9-811b-62cf53d51362.png">

-- Your password should be sitting in plain text in the console log (you may need to scroll up a bit.)
-- 
<img width="807" alt="Screen Shot 2019-05-09 at 10 57 39 AM" src="https://user-images.githubusercontent.com/48080138/57468055-58d45400-7249-11e9-9b49-c327f6470976.png">
-- You can see if this screenshot that the password to my camera's RTSP feed is v0tz_...


- Next step is to get the ID#'s of all the cameras on your system. This is easy enough through the node platform.
-- follow [Tim's directions](https://github.com/timcharper/homebridge-vivint/issues/2#issuecomment-465332969) to create a debugging node
-- use the following line: `systemInfo.system.par[0].d.forEach((d) => console.log("name: " + d.n + " id: " + d._id + " ciu: " + d.ciu))`
-- that will print a list of all the devices, along with all of the id#s, and a copy of the RTSP feed line.
-- 
<img width="1000" alt="Screen Shot 2019-05-09 at 11 13 23 AM" src="https://user-images.githubusercontent.com/48080138/57469139-8cb07900-724b-11e9-8b50-84a42f4a672c.png">

-- You can see here that I have 5 cameras, ids 22, 24, 52, 55, and 62. There is also a pattern, RTSP://[panel_ip]:8554/Video-[ID#]

-- You should now have everything you need to add the cameras to HomeKit

- Configure homebridge-camera-ffmpeg
-- Now we need to put the cameras found into our config.json file. It's pretty simple at this point, the username for the stream will be "user" and the password will be what you found before. To test the stream, you can open VLC with this address: RTSP://user:[insert password]@[insert IP]/Video-[insert ID]
-- I'll just paste my config.json file:
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "platforms": [
	{
		"platform": "Vivint",
		"name": "homebridge-vivint",
		"username": "dxxxxxx@gmail.com",
		"password": "xxxxxxxxxx",
		"apiLoginRefreshSecs": 600,
		"lowbatterylevel": 20
	}, {
		"platform": "Camera-ffmpeg",
		"cameras": [
      {
              "name": "Living Room Camera",
              "videoConfig": {
                      "source": "-rtsp_transport tcp -re -i rtsp://user:v0tz_xxxxxxxxx@192.168.0.20:8554/Video-24",
                      "maxStreams": 2,
                      "maxWidth": 1280,
                      "maxHeight": 720,
                      "maxFPS": 30,
                      "audio": true,
                      "packetSize": 188
              }
      },
      {
              "name": "Baby Camera",
              "videoConfig": {
                      "source": "-rtsp_transport tcp -re -i rtsp://user:v0tz_xxxxxxxx@192.168.0.20:8554/Video-22",
                      "maxStreams": 2,
                      "maxWidth": 1280,
                      "maxHeight": 720,
                      "maxFPS": 30,
                      "audio": true,
                      "packetSize": 188
              }
      },
      {
              "name": "Backyard Camera",
              "videoConfig": {
                      "source": "-rtsp_transport tcp -re -i rtsp://user:v0tz_xxxxxxxx@192.168.0.20:8554/Video-52",
                      "maxStreams": 2,
                      "maxWidth": 1280,
                      "maxHeight": 720,
                      "maxFPS": 30,
                      "audio": false,
                      "packetSize": 188
              }
      },
      {
              "name": "Doorbell Camera",
              "videoConfig": {
                      "source": "-rtsp_transport tcp -re -i rtsp://user:v0tz_xxxxxxxxxx@192.168.0.20:8554/Video-55",
                      "maxStreams": 2,
                      "maxWidth": 800,
                      "maxHeight": 450,
                      "maxFPS": 30,
                      "audio": true,
                      "packetSize": 188
              }
      },
      {
              "name": "Driveway Camera",
              "videoConfig": {
                      "source": "-rtsp_transport tcp -re -i rtsp://user:xxxxxxxxx@192.168.0.20:8554/Video-62",
                      "maxStreams": 2,
                      "maxWidth": 1280,
                      "maxHeight": 720,
                      "maxFPS": 30,
                      "audio": false,
                      "packetSize": 188
              }
      }

		]
	}
    ],
    "accessories": []
}

```

-- note that audio:true/false depends on the camera.. my outdoor cameras don't have audio so I don't enable the audio feed for those cameras. 
-- all said and done, you should have vivint cameras in your feed 👍 
<img width="958" alt="Screen Shot 2019-05-09 at 11 21 17 AM" src="https://user-images.githubusercontent.com/48080138/57469584-9be3f680-724c-11e9-8c08-1603e842b117.png">

**Comment by rob74lee** [comment]
This is awesome! The only part I don't understand is Tim's piece. I don't understand how to get the id's of the cameras. I have my password and IP address but I don't know how to run this node to get the id's. Aren't the id's the same as when you see the id when logging into the installer box on the panel? Just curious.

**Comment by daymondm** [comment]
Possibly? 



I'm not sure.. to open a node terminal in windows, I believe you hit windows key+R and type cmd to get a command prompt.

make sure you are in the directory that the plugin is installed:
```
Daymonds-iMac:~ daymondm$ cd /usr/local/lib/node_modules/homebridge-vivint/
Daymonds-iMac:homebridge-vivint daymondm$ pwd
/usr/local/lib/node_modules/homebridge-vivint
Daymonds-iMac:homebridge-vivint daymondm$ ls
README.md	index.js	lib		node_modules	package.json	test
Daymonds-iMac:homebridge-vivint daymondm$ 

```

 then I think you ought to be able to just type "node" and get a node terminal. You should see something like this:

```
Daymonds-iMac:homebridge-vivint daymondm$ node
Welcome to Node.js v12.1.0.
Type ".help" for more information.
> 
```


then just copy and paste, one line at a time:

```
const fs = require("fs")
const request = require("request-promise-native")
const VivintApiModule = require("./lib/vivint_api.js")
const VivintApi = VivintApiModule({apiLoginRefreshSecs: 1200}, console.log)
creds = {
"username": "your@email.com",
"password": "your-vivint-password"
}

let apiPromise = VivintApi.login(creds)

function getPromise(p) {
  var r = {}
  p.then((_r) => r.value = _r)
  return r
}

_api = getPromise(apiPromise)
api = _api.value;

api.systemInfo.system.par[0].d.forEach((d) => console.log("name: " + d.n + " id: " + d._id + " ciu: " + d.ciu))
```

should result something along the lines of:

```
> api.systemInfo.system.par[0].d.forEach((d) => console.log("name: " + d.n + " id: " + d._id + " ciu: " + d.ciu))
name: undefined id: 20003 ciu: undefined
name: undefined id: 5 ciu: undefined
name: undefined id: 11 ciu: undefined
name: Panel id: 12 ciu: undefined
name: Baby Camera id: 22 ciu: rtsp://192.168.0.20:8554/Video-22
name: Living Room Camera id: 24 ciu: rtsp://192.168.0.20:8554/Video-24
name: Garage Door id: 27 ciu: undefined
name: Front Door Lock id: 29 ciu: undefined
name: Front Door id: 32 ciu: undefined
name: Back Door id: 33 ciu: undefined
name: Garage Door id: 34 ciu: undefined
name: Motion Detector id: 35 ciu: undefined
name: Motion Detector id: 36 ciu: undefined
name: Glass Break id: 37 ciu: undefined
name: Master Bedroom One Window id: 38 ciu: undefined
name: Master Bedroom Two Window id: 39 ciu: undefined
name: Bedroom One Window id: 40 ciu: undefined
name: Bedroom Two Window id: 41 ciu: undefined
name: Back Door Lock id: 42 ciu: undefined
name: Hallway Smoke Detector id: 47 ciu: undefined
name: Hallway Smoke Detector - Heat id: 48 ciu: undefined
name: Hallway Smoke Detector - Freeze id: 49 ciu: undefined
name: Backyard Camera id: 52 ciu: rtsp://192.168.0.20:8554/Video-52
name: undefined id: 21 ciu: undefined
name: Doorbell id: 55 ciu: rtsp://192.168.0.20:8554/Video-55
name: Hallway Smoke Detector id: 56 ciu: undefined
name: dlinkap id: 58 ciu: undefined
name: dlinkap id: 61 ciu: undefined
name: Driveway Camera id: 62 ciu: rtsp://192.168.0.20:8554/Video-62
undefined
> 
```


I don't have access to the installer toolbox at the moment, but if the ID numbers in there look similar to those that I have above, you could go for it. 

An easy way to test it would be to open VLC (maybe even internet explorer or chrome?) to the RTSP address. RTSP://user:INSERT_RTSP_PASSWORD@INSERT_PANEL_IP:8554/Video-INSTERT_ID_NUMBER

so, for mine as listed above:
RTSP://user:v0tz_xxxxxxx@192.168.0.20:8554/Video-62 brings up a live feed of my driveway camera

**Comment by daymondm** [comment]
Fun fact, you can't preview the stream on the same computer that Homebridge (FFmpeg) is running on. They apparently try to bind to the same port. There went 30 minutes of my life.

**Comment by rob74lee** [comment]
I filled your email Line by line and this is all I get:
<img width="1440" alt="Screen Shot 2019-05-11 at 6 08 55 AM" src="https://user-images.githubusercontent.com/34845423/57568932-92c16980-73b3-11e9-9206-1361508bc766.png">
Am I doing something wrong?

**Comment by rob74lee** [comment]
I complete this line by line but I keep getting a syntax error at my username for some reason. After entering all of this I get nothing.

**Comment by daymondm** [comment]
I think your Mac is changing the “ to a different character? I’m not sure but in the pic you sent me they are kind of italicized unlike the rest of them

**Comment by daymondm** [comment]
Found some information [https://apple.stackexchange.com/questions/120486/quotes-problem-in-mavericks-or-textedit] about that

**Comment by rob74lee** [comment]
That was it! I manually entered my info and it worked like a charm!!!! Thank you so much my friend!

**Comment by rob74lee** [comment]
Good morning sir,

Have you noticed on your end any issues with the cameras showing in Homekit? It worked like a charm but the last few weeks since I have updated to IOS 13 the camera feeds won't show. Just curious if it is a problem on my end or not. Thanks!

**Comment by daymondm** [comment]
> Good morning sir,
> 
> Have you noticed on your end any issues with the cameras showing in Homekit? It worked like a charm but the last few weeks since I have updated to IOS 13 the camera feeds won't show. Just curious if it is a problem on my end or not. Thanks!

I have noticed that if my WiFi goes down, the IP address of the panel changes. You can probably set up a static ip based on the panels MAC address but I haven’t messed with it.

**Comment by forresthamilton** [comment]
I just wanted to add one camera to test it. It showed up in HK after adding and entering the code but it says the camera is not responding. I am receiving this on repeat:
[4/15/2020, 10:13:03 AM] [Camera-ffmpeg] Start streaming video from Doorbell Camera with 640:360@30fps (132kBit)
[4/15/2020, 10:13:04 AM] [Vivint] received pubNub msg
[4/15/2020, 10:13:04 AM] [Vivint] {"_id":"6665697450284799|1","da":{"d":[{"_id":12,"wst":2}],"plctx":{"context_carrier":{"previous_handler":"Subscriber Update Handler","tracing_context":{"uber-trace-id":"1244b9043140a724:1244b9043140a724:0:0"}},"mid":"5e97167096e2350001abc874","ts":"2020-04-15T14:13:04.429"}},"op":"u","panid":6665697450284799,"parid":1,"t":"account_partition"}
[4/15/2020, 10:13:06 AM] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

**Comment by rob74lee** [comment]
Did you try running it through the json lint to check for errors? The url is https://jsonlint.com <https://jsonlint.com/>.

**Comment by forresthamilton** [comment]
I fixed the config file but am receiving no response in HK for the doorbell camera, I can view live video if I go to the rtsp feed in VLC.

**Comment by forresthamilton** [comment]
I feel like there is something I need to do besides download the ffmpeg tar.bz2 and unzip it.

**Comment by forresthamilton** [comment]
> Possibly?
> 
> I'm not sure.. to open a node terminal in windows, I believe you hit windows key+R and type cmd to get a command prompt.
> 
> make sure you are in the directory that the plugin is installed:
> 
> ```
> Daymonds-iMac:~ daymondm$ cd /usr/local/lib/node_modules/homebridge-vivint/
> Daymonds-iMac:homebridge-vivint daymondm$ pwd
> /usr/local/lib/node_modules/homebridge-vivint
> Daymonds-iMac:homebridge-vivint daymondm$ ls
> README.md	index.js	lib		node_modules	package.json	test
> Daymonds-iMac:homebridge-vivint daymondm$ 
> ```
> 
> then I think you ought to be able to just type "node" and get a node terminal. You should see something like this:
> 
> ```
> Daymonds-iMac:homebridge-vivint daymondm$ node
> Welcome to Node.js v12.1.0.
> Type ".help" for more information.
> > 
> ```
> 
> then just copy and paste, one line at a time:
> 
> ```
> const fs = require("fs")
> const request = require("request-promise-native")
> const VivintApiModule = require("./lib/vivint_api.js")
> const VivintApi = VivintApiModule({apiLoginRefreshSecs: 1200}, console.log)
> creds = {
> "username": "your@email.com",
> "password": "your-vivint-password"
> }
> 
> let apiPromise = VivintApi.login(creds)
> 
> function getPromise(p) {
>   var r = {}
>   p.then((_r) => r.value = _r)
>   return r
> }
> 
> _api = getPromise(apiPromise)
> api = _api.value;
> 
> api.systemInfo.system.par[0].d.forEach((d) => console.log("name: " + d.n + " id: " + d._id + " ciu: " + d.ciu))
> ```
> 
> should result something along the lines of:
> 
> ```
> > api.systemInfo.system.par[0].d.forEach((d) => console.log("name: " + d.n + " id: " + d._id + " ciu: " + d.ciu))
> name: undefined id: 20003 ciu: undefined
> name: undefined id: 5 ciu: undefined
> name: undefined id: 11 ciu: undefined
> name: Panel id: 12 ciu: undefined
> name: Baby Camera id: 22 ciu: rtsp://192.168.0.20:8554/Video-22
> name: Living Room Camera id: 24 ciu: rtsp://192.168.0.20:8554/Video-24
> name: Garage Door id: 27 ciu: undefined
> name: Front Door Lock id: 29 ciu: undefined
> name: Front Door id: 32 ciu: undefined
> name: Back Door id: 33 ciu: undefined
> name: Garage Door id: 34 ciu: undefined
> name: Motion Detector id: 35 ciu: undefined
> name: Motion Detector id: 36 ciu: undefined
> name: Glass Break id: 37 ciu: undefined
> name: Master Bedroom One Window id: 38 ciu: undefined
> name: Master Bedroom Two Window id: 39 ciu: undefined
> name: Bedroom One Window id: 40 ciu: undefined
> name: Bedroom Two Window id: 41 ciu: undefined
> name: Back Door Lock id: 42 ciu: undefined
> name: Hallway Smoke Detector id: 47 ciu: undefined
> name: Hallway Smoke Detector - Heat id: 48 ciu: undefined
> name: Hallway Smoke Detector - Freeze id: 49 ciu: undefined
> name: Backyard Camera id: 52 ciu: rtsp://192.168.0.20:8554/Video-52
> name: undefined id: 21 ciu: undefined
> name: Doorbell id: 55 ciu: rtsp://192.168.0.20:8554/Video-55
> name: Hallway Smoke Detector id: 56 ciu: undefined
> name: dlinkap id: 58 ciu: undefined
> name: dlinkap id: 61 ciu: undefined
> name: Driveway Camera id: 62 ciu: rtsp://192.168.0.20:8554/Video-62
> undefined
> > 
> ```
> 
> I don't have access to the installer toolbox at the moment, but if the ID numbers in there look similar to those that I have above, you could go for it.
> 
> An easy way to test it would be to open VLC (maybe even internet explorer or chrome?) to the RTSP address. RTSP://user:INSERT_RTSP_PASSWORD@INSERT_PANEL_IP:8554/Video-INSTERT_ID_NUMBER
> 
> so, for mine as listed above:
> RTSP://user:v0tz_xxxxxxx@192.168.0.20:8554/Video-62 brings up a live feed of my driveway camera

I was able to view a live feed of my doorbell the other day through VLC and add the camera into HK although I am not able to view live feed in HK.

**Comment by forresthamilton** [comment]
Also, the node part to get the IDs didn't work for me. Is the ID for PIVMotion the same as the camera?

**Comment by jonathanware** [comment]
Maybe a silly question, but I have a single vivint camera (an ADC-V520IR) is it possible to get this process going with just the camera? Or will I need a vivint panel too?

**Comment by jcdelacruz23** [comment]
Few things I can't figure out is how to get my camera ID and RTS.  And how to create a debugging node in order to get those information.  Please help
